{
 "title": "SERVICE_NAME",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "quantile", "query": "0.99,0.95,0.9,0.8,0.7,0.6,0.5" },
   { "name": "cluster", "query": "prod" },
   { "name": "service_name", "query": "SERVICE_NAME" }
  ]
 },
 "panels": [
  {
   "title": "Kubernetes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "container_memory_working_set_bytes{container!=\"POD\",container!=\"\",pod=~\"$service_name.*\", cluster=\"$cluster\"}",
       "legendFormat": "{{pod}} - Usage"
      }
     ]
    },
    {
     "title": "CPU Throttling",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(increase(container_cpu_cfs_throttled_periods_total{pod=~\"$service_name.*\", container!=\"\"}[5m])) by (container, pod) /sum(increase(container_cpu_cfs_periods_total{pod=~\"$service_name.*\", container!=\"\"}[5m])) by (container, pod)",
       "legendFormat": "{{container}} in {{pod}}"
      }
     ]
    },
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"$service_name.*\", image!=\"\", container!=\"POD\", cluster=\"$cluster\"}[5m])) by (pod, container)",
       "legendFormat": "{{container}} in {{pod}}"
      }
     ]
    },
    {
     "title": "Ingress Errors",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(nginx_ingress_controller_requests{ingress=~\"$service_name\", status!~\"(2|3).*\"}[2m])) by (status)",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Pod Count",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(kube_pod_info{pod=~\"$service_name.*\",pod!~\".*kafka.*\"})",
       "legendFormat": "Main Pods"
      },
      {
       "expr": "count(kube_pod_info{pod=~\"$service_name.*\",pod=~\".*kafka.*\"})",
       "legendFormat": "Kafka Pods"
      }
     ]
    },
    {
     "title": "Pod Container Restarts",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(kube_pod_container_status_restarts_total{pod=~\"$service_name-.*\"}[2m])) by (container, pod)",
       "legendFormat": "{{container}} in {{pod}}"
      }
     ]
    }
   ]
  },
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "HTTP Success Count",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{app=\"$service_name\", cluster=\"$cluster\", path!~\".*openapi.*\", status_code!~\"(4|5)..\"}[5m])) by (method, path, status_code)",
     "legendFormat": "{{method}}  {{path}} {{status_code}}"
    }
   ]
  },
  {
   "title": "HTTP Execution Time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 2 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($quantile, sum(rate(http_request_duration_seconds_bucket{app=\"$service_name\", status_code!~\"(4|5)..\", cluster=\"$cluster\"}[5m])) by (status_code, path, method, le))",
     "legendFormat": "{{method}}  {{path}} {{status_code}}"
    }
   ]
  },
  {
   "title": "HTTP Error Count",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{app=\"$service_name\", cluster=\"$cluster\", status_code=~\"(4|5)..\"}[5m])) by (method, path, status_code)",
     "legendFormat": "{{method}}  {{path}} {{status_code}}"
    }
   ]
  },
  {
   "title": "Mongo",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true
  },
  {
   "title": "Mongo Success Count",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(mongo_count{app=\"$service_name\", cluster=\"$cluster\", result=\"success\"}[5m])) by (method) ",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Mongo Execution Time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($quantile, sum(rate(mongo_execution_time_bucket{app=\"$service_name\", cluster=\"$cluster\", result=\"success\"}[5m])) by (method, le))",
     "legendFormat": "{{method}} "
    }
   ]
  },
  {
   "title": "Mongo Error Count",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(mongo_count{app=\"$service_name\", cluster=\"$cluster\", result=\"error\"}[5m])) by (method) ",
     "legendFormat": "{{method}}  {{path}} {{status_code}}"
    }
   ]
  },
  { "title": "Producer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Producer Success Count",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(producer_count{app=\"$service_name\", result=\"success\"}[5m])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Producer Execution Time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($quantile, sum(rate(producer_execution_time_bucket{app=\"$service_name\"}[5m])) by (le, method))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Producer Error Count",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(producer_count{app=\"$service_name\", result=\"error\"}[5m])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  }
 ]
}